export const QUESTIONS = [

// ══════════════════════════════════════════════════════
// TOPIC: LAKEHOUSE FUNDAMENTALS (40 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:101, topic:"lakehouse", sub:"Architecture", diff:"Beginner", type:"mcq", q:"What is the Databricks Lakehouse Platform primarily designed to do?", opts:["Replace data warehouses only","Combine data lake flexibility with data warehouse reliability","Store only structured data","Run only ML workloads"], a:1, exp:"The Lakehouse combines the scalability and low cost of data lakes with the reliability, ACID transactions, and performance of data warehouses." },
{ id:102, topic:"lakehouse", sub:"Clusters", diff:"Beginner", type:"tf", q:'"All-Purpose clusters are the most cost-effective option for running automated production jobs."', opts:["TRUE","FALSE"], a:1, exp:"Job clusters are cheaper for automated workloads — they start fresh per run and terminate when done. All-Purpose clusters are for interactive development." },
{ id:103, topic:"lakehouse", sub:"Workspace", diff:"Beginner", type:"mcq", q:"Which of the following is NOT a valid Databricks cluster mode?", opts:["Single Node","Standard (Multi-node)","High Concurrency","Auto-Scaling Only"], a:3, exp:"Auto-Scaling Only is not a cluster mode. Single Node, Standard, and High Concurrency (now deprecated in favour of Shared) are valid modes." },
{ id:104, topic:"lakehouse", sub:"Notebooks", diff:"Beginner", type:"mcq", q:"Which languages can be used natively in a Databricks notebook?", opts:["Python only","Python and SQL only","Python, SQL, R, and Scala","Python, SQL, R, Scala, and Java"], a:2, exp:"Databricks notebooks natively support Python, SQL, R, and Scala. Java is not a native notebook language." },
{ id:105, topic:"lakehouse", sub:"DBFS", diff:"Beginner", type:"tf", q:'"DBFS (Databricks File System) is a distributed file system mounted on every Databricks cluster."', opts:["TRUE","FALSE"], a:0, exp:"DBFS is a distributed filesystem abstraction layer that comes pre-mounted on Databricks clusters, backed by cloud object storage." },
{ id:106, topic:"lakehouse", sub:"Architecture", diff:"Beginner", type:"mcq", q:"What layer in the Lakehouse architecture ensures data reliability and ACID transactions?", opts:["Bronze layer","Delta Lake","Parquet files","Apache Spark"], a:1, exp:"Delta Lake is the storage layer that brings ACID transactions, scalable metadata handling, and data versioning to the Lakehouse." },
{ id:107, topic:"lakehouse", sub:"Clusters", diff:"Beginner", type:"mcq", q:"What happens to a Job cluster when the job completes?", opts:["It stays running for 30 minutes","It converts to an All-Purpose cluster","It automatically terminates","It pauses and waits for the next run"], a:2, exp:"Job clusters are ephemeral — they start when a job begins and terminate when it completes, saving costs." },
{ id:108, topic:"lakehouse", sub:"Workspace", diff:"Beginner", type:"mcq", q:"Where are Databricks notebooks stored by default?", opts:["DBFS","Cloud object storage","Workspace file system","Git repository"], a:2, exp:"Notebooks are stored in the Databricks Workspace file system by default, though they can be synced to Git via Repos." },
{ id:109, topic:"lakehouse", sub:"Architecture", diff:"Beginner", type:"tf", q:'"The Bronze layer in a Medallion architecture stores raw, unprocessed data exactly as received from source systems."', opts:["TRUE","FALSE"], a:0, exp:"Bronze stores raw ingested data with minimal transformation, preserving the original source data for reprocessing if needed." },
{ id:110, topic:"lakehouse", sub:"Clusters", diff:"Beginner", type:"mcq", q:"What is the minimum number of nodes in a Single Node cluster?", opts:["0","1","2","3"], a:1, exp:"A Single Node cluster has exactly 1 node that acts as both driver and worker. It has no worker nodes." },

// --- Intermediate ---
{ id:111, topic:"lakehouse", sub:"Repos", diff:"Intermediate", type:"mcq", q:"You want Git version control for notebooks without manual exports. Which feature enables this?", opts:["Databricks Connect","Export as .py manually","Store in DBFS","Databricks Repos (Git folders)"], a:3, exp:"Databricks Repos provides native Git integration directly in the workspace for version control of notebooks and files." },
{ id:112, topic:"lakehouse", sub:"Clusters", diff:"Intermediate", type:"mcq", q:"Which cluster policy feature allows admins to restrict the instance types users can select?", opts:["Access Control Lists","Cluster policies","IAM roles","Workspace settings"], a:1, exp:"Cluster policies allow admins to enforce cost controls and security by limiting which configuration options users can modify." },
{ id:113, topic:"lakehouse", sub:"Architecture", diff:"Intermediate", type:"mcq", q:"In the Medallion architecture, what is the primary purpose of the Gold layer?", opts:["Raw data storage","Clean validated data","Business-level aggregates ready for consumption","ML feature store"], a:2, exp:"The Gold layer contains business-level aggregations, refined data models, and reporting-ready datasets." },
{ id:114, topic:"lakehouse", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"A Databricks Job has 3 tasks: A, B, C. B and C both depend on A. How does Databricks execute them?", opts:["A then B then C sequentially","A then B and C in parallel","B and C then A","All three in parallel"], a:1, exp:"When B and C both depend on A but not on each other, Databricks runs A first, then executes B and C in parallel." },
{ id:115, topic:"lakehouse", sub:"Workspace", diff:"Intermediate", type:"mcq", q:"What is the difference between a Databricks Secret Scope and a Secret?", opts:["They are the same thing","A scope is a collection of secrets; a secret is a key-value pair within a scope","A secret is a collection of scopes","Scopes are only for Azure, secrets are for AWS"], a:1, exp:"A Secret Scope is a named container (backed by Databricks or Azure Key Vault) that holds multiple secrets as key-value pairs." },
{ id:116, topic:"lakehouse", sub:"Clusters", diff:"Intermediate", type:"tf", q:'"Photon is a vectorized query engine that accelerates SQL and DataFrame workloads and is available on all cluster types."', opts:["TRUE","FALSE"], a:1, exp:"Photon is available on specific compute types and requires Databricks Runtime. It is not available on all cluster types or runtimes." },
{ id:117, topic:"lakehouse", sub:"Architecture", diff:"Intermediate", type:"mcq", q:"Which Databricks feature allows you to share data across workspaces without copying it?", opts:["DBFS mounts","Delta Sharing","Data Replication","Databricks Connect"], a:1, exp:"Delta Sharing is an open protocol for secure real-time data sharing across organizations and platforms without data copying." },
{ id:118, topic:"lakehouse", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"Which retry policy setting controls how many times a failed task is retried in a Databricks Job?", opts:["max_retries in the job config","spark.task.maxFailures","cluster.retryOnFailure","taskRetryLimit in the cluster policy"], a:0, exp:"max_retries is set in the job/task configuration and controls how many times Databricks retries a failed task." },
{ id:119, topic:"lakehouse", sub:"Workspace", diff:"Intermediate", type:"mcq", q:"What is the purpose of Databricks Widgets in notebooks?", opts:["To display charts","To create parameterized notebooks that accept input values","To share notebooks externally","To schedule notebook runs"], a:1, exp:"Widgets allow notebooks to accept parameters when run as jobs or called from other notebooks, making them reusable and configurable." },
{ id:120, topic:"lakehouse", sub:"Architecture", diff:"Intermediate", type:"mcq", q:"Which statement about the Databricks Control Plane is correct?", opts:["It stores customer data","It runs Spark jobs","It manages workspace metadata, clusters, and the web UI","It is deployed in the customer's cloud account"], a:2, exp:"The Control Plane (managed by Databricks) handles workspace metadata, cluster management, job scheduling, and the UI. Customer data stays in the Data Plane." },

// --- Advanced ---
{ id:121, topic:"lakehouse", sub:"Architecture", diff:"Advanced", type:"mcq", q:"A company needs to run Databricks notebooks from their existing cloud VPC with strict network controls. Which feature enables this?", opts:["VPC Peering only","Databricks on GCP","Customer-managed VPC (No Public IP / Private Link)","DBFS mount points"], a:2, exp:"Customer-managed VPCs with Private Link/No Public IP deployment keeps all traffic within the customer's network boundary." },
{ id:122, topic:"lakehouse", sub:"Clusters", diff:"Advanced", type:"mcq", q:"You need to minimize cold start time for interactive clusters used sporadically throughout the day. What is the best approach?", opts:["Use a Single Node cluster","Enable cluster pinning","Use instance pools with pre-warmed instances","Increase max workers"], a:2, exp:"Instance pools maintain pre-warmed instances in a ready state, dramatically reducing cluster start times for both interactive and job clusters." },
{ id:123, topic:"lakehouse", sub:"Jobs", diff:"Advanced", type:"mcq", q:"A Databricks Job using a shared job cluster across tasks fails at task C. What happens to the cluster?", opts:["The cluster terminates immediately","The cluster stays running for remaining tasks","The cluster restarts automatically","The cluster converts to All-Purpose"], a:1, exp:"With shared job clusters, the cluster stays alive for the duration of the job run and terminates when all tasks complete or the job fails definitively." },
{ id:124, topic:"lakehouse", sub:"Workspace", diff:"Advanced", type:"mcq", q:"Which Databricks feature provides row-level and column-level security on Delta tables?", opts:["Table ACLs only","Unity Catalog with row/column filters","DBFS permissions","Spark SQL GRANT statements only"], a:1, exp:"Unity Catalog supports row-level security via row filters and column-level security via column masks, enforced across all query engines." },
{ id:125, topic:"lakehouse", sub:"Architecture", diff:"Advanced", type:"mcq", q:"Your team runs thousands of small Spark jobs. Cold start latency is a major issue. Which combination best addresses this?", opts:["Larger clusters + Auto Scaling","Instance Pools + Job Clusters","All-Purpose clusters + keep alive","Serverless compute + pools"], a:1, exp:"Instance Pools pre-warm VMs, and Job Clusters attach to them instantly. This combination gives low latency without the cost of keeping All-Purpose clusters alive." },

// ══════════════════════════════════════════════════════
// TOPIC: DELTA LAKE (40 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:201, topic:"delta", sub:"ACID", diff:"Beginner", type:"mcq", q:"What does ACID stand for in the context of Delta Lake?", opts:["Atomicity, Consistency, Isolation, Durability","Automatic, Concurrent, Integrated, Distributed","Access, Control, Index, Data","Atomic, Consistent, Indexed, Durable"], a:0, exp:"ACID stands for Atomicity, Consistency, Isolation, and Durability — the four properties that guarantee database transaction reliability." },
{ id:202, topic:"delta", sub:"Time Travel", diff:"Beginner", type:"mcq", q:"Which Delta Lake feature enables querying historical versions of a table?", opts:["MERGE INTO","Time Travel","CLONE","VACUUM"], a:1, exp:"Delta Lake Time Travel lets you query historical snapshots using VERSION AS OF or TIMESTAMP AS OF syntax." },
{ id:203, topic:"delta", sub:"Maintenance", diff:"Beginner", type:"mcq", q:"What does the VACUUM command do in Delta Lake?", opts:["Compacts small files into larger ones","Removes old transaction log entries","Deletes data files no longer referenced by the current table version","Refreshes table statistics"], a:2, exp:"VACUUM removes data files no longer referenced by the Delta table that are older than the retention threshold (default 7 days)." },
{ id:204, topic:"delta", sub:"ACID", diff:"Beginner", type:"tf", q:'"Delta Lake supports concurrent reads and writes without locking the entire table."', opts:["TRUE","FALSE"], a:0, exp:"Delta Lake uses optimistic concurrency control, allowing concurrent reads and writes. Conflicts are detected and resolved at commit time." },
{ id:205, topic:"delta", sub:"Schema", diff:"Beginner", type:"mcq", q:"What happens when you write data to a Delta table with a column that does not exist in the table schema by default?", opts:["The new column is automatically added","The write fails with a schema mismatch error","The new column is silently dropped","The entire table is recreated"], a:1, exp:"By default Delta Lake enforces schema — writes with extra columns fail. You must explicitly enable schema evolution with mergeSchema=true." },
{ id:206, topic:"delta", sub:"Format", diff:"Beginner", type:"mcq", q:"What file format does Delta Lake use to store data?", opts:["ORC","Avro","Parquet","CSV"], a:2, exp:"Delta Lake stores data in Parquet format, adding a transaction log (_delta_log) on top to provide ACID guarantees." },
{ id:207, topic:"delta", sub:"Transaction Log", diff:"Beginner", type:"mcq", q:"Where does Delta Lake store its transaction log?", opts:["In a separate database","In the _delta_log directory within the table path","In DBFS root","In the cluster driver logs"], a:1, exp:"The transaction log is stored as JSON files in the _delta_log directory at the root of the Delta table path." },
{ id:208, topic:"delta", sub:"Maintenance", diff:"Beginner", type:"tf", q:'"Running OPTIMIZE on a Delta table permanently deletes old data files."', opts:["TRUE","FALSE"], a:1, exp:"OPTIMIZE creates new compacted files but does NOT delete old files. VACUUM is needed to physically remove old unreferenced files." },
{ id:209, topic:"delta", sub:"Time Travel", diff:"Beginner", type:"mcq", q:"What is the default data retention period for Delta Lake Time Travel?", opts:["1 day","7 days","30 days","90 days"], a:1, exp:"The default retention period is 7 days. Files older than this can be removed by VACUUM. This can be configured with delta.logRetentionDuration." },
{ id:210, topic:"delta", sub:"ACID", diff:"Beginner", type:"mcq", q:"Which operation in Delta Lake allows you to insert new records and update existing ones in a single statement?", opts:["INSERT OVERWRITE","UPDATE","MERGE INTO","COPY INTO"], a:2, exp:"MERGE INTO (also called upsert) matches source and target rows and can insert, update, or delete based on matching conditions." },

// --- Intermediate ---
{ id:211, topic:"delta", sub:"Optimization", diff:"Intermediate", type:"mcq", q:"OPTIMIZE with ZORDER BY is used to:", opts:["Sort the table alphabetically","Co-locate related data in the same files to improve filter query performance","Remove duplicate rows","Partition data by date automatically"], a:1, exp:"ZORDER BY co-locates related data in the same files, reducing the amount of data scanned for queries with filters on the Z-ordered columns." },
{ id:212, topic:"delta", sub:"CDF", diff:"Intermediate", type:"tf", q:'"You must restart a streaming query to start consuming Change Data Feed from an existing Delta table."', opts:["TRUE","FALSE"], a:1, exp:"No restart needed. Set readChangeFeed=true on the existing stream and optionally specify startingVersion to begin consuming CDC events." },
{ id:213, topic:"delta", sub:"Optimization", diff:"Intermediate", type:"mcq", q:"Liquid Clustering is different from traditional ZORDER because:", opts:["It uses partitions instead of file co-location","It is incremental — each OPTIMIZE only rewrites unclustered files","It requires more manual tuning","It only works on string columns"], a:1, exp:"Liquid Clustering is incremental by design — OPTIMIZE only rewrites files not yet clustered, making repeated runs efficient." },
{ id:214, topic:"delta", sub:"Schema", diff:"Intermediate", type:"mcq", q:"How do you enable schema evolution when writing a DataFrame to a Delta table?", opts:["Set spark.sql.schema.evolution=true","Use .option('mergeSchema', 'true') or spark.databricks.delta.schema.autoMerge.enabled=true","Recreate the table with the new schema first","Use INSERT OVERWRITE"], a:1, exp:"Schema evolution is enabled per-write with .option('mergeSchema','true') or globally with the autoMerge Spark config." },
{ id:215, topic:"delta", sub:"Time Travel", diff:"Intermediate", type:"mcq", q:"You need to restore a Delta table to its state from 2 days ago. Which command achieves this?", opts:["RESTORE TABLE my_table TO TIMESTAMP AS OF '2 days ago'","SELECT * FROM my_table TIMESTAMP AS OF date_sub(now(), 2)","ROLLBACK TABLE my_table","ALTER TABLE my_table RESTORE VERSION 0"], a:0, exp:"RESTORE TABLE ... TO TIMESTAMP AS OF restores the table to its state at the specified timestamp, creating a new version." },
{ id:216, topic:"delta", sub:"Maintenance", diff:"Intermediate", type:"mcq", q:"What is the risk of setting delta.deletedFileRetentionDuration to 0 hours?", opts:["Slower writes","Loss of Time Travel history and potential data loss if streams are running","Higher storage costs","Partition corruption"], a:1, exp:"Setting retention to 0 allows VACUUM to immediately delete files, breaking time travel and potentially causing failures for streaming queries reading those files." },
{ id:217, topic:"delta", sub:"ACID", diff:"Intermediate", type:"mcq", q:"Two writers attempt to update different partitions of the same Delta table simultaneously. What happens?", opts:["Both fail due to write conflict","One succeeds, one fails","Both succeed — Delta allows concurrent partition-level writes","The second write is queued"], a:2, exp:"Delta Lake supports concurrent writes to different partitions using optimistic concurrency. Both succeed as they modify disjoint data." },
{ id:218, topic:"delta", sub:"CDF", diff:"Intermediate", type:"mcq", q:"Change Data Feed captures which types of row-level changes?", opts:["INSERT only","INSERT and UPDATE only","INSERT, UPDATE, and DELETE","INSERT, UPDATE, DELETE, and SCHEMA CHANGE"], a:2, exp:"CDF captures insert, update (pre and post images), and delete operations at the row level." },
{ id:219, topic:"delta", sub:"Format", diff:"Intermediate", type:"mcq", q:"What is stored in Delta Lake checkpoint files?", opts:["Raw data in Parquet format","A complete snapshot of the table state at that version, replacing older JSON log files","Schema definitions only","Partition metadata only"], a:1, exp:"Checkpoint files (written every 10 commits by default) contain the complete table state, allowing faster metadata loading without reading all JSON log files." },
{ id:220, topic:"delta", sub:"Optimization", diff:"Intermediate", type:"mcq", q:"What does the Auto Optimize feature in Delta Lake do?", opts:["Automatically runs VACUUM","Automatically compacts small files during writes and applies OPTIMIZE after writes","Automatically adds partitions","Automatically merges schema changes"], a:1, exp:"Auto Optimize consists of Optimized Writes (produces fewer larger files) and Auto Compaction (runs OPTIMIZE on files post-write) enabled via table properties." },

// --- Advanced ---
{ id:221, topic:"delta", sub:"ACID", diff:"Advanced", type:"mcq", q:"A streaming writer and a batch DELETE run concurrently on the same Delta table. What is the expected outcome?", opts:["Both fail","The stream fails, DELETE succeeds","Both succeed — Delta handles concurrent stream and batch operations","DELETE is blocked until the stream checkpoints"], a:2, exp:"Delta Lake's optimistic concurrency allows concurrent streaming writes and batch operations. Delta detects and resolves conflicts at commit time." },
{ id:222, topic:"delta", sub:"Optimization", diff:"Advanced", type:"mcq", q:"You have a 10TB Delta table queried heavily on event_date and user_id. What is the optimal strategy?", opts:["Partition by user_id + ZORDER by event_date","Partition by event_date + ZORDER by user_id","ZORDER by both without partitioning","Partition by both columns"], a:1, exp:"Partition by the low-cardinality column (event_date) for file pruning, then ZORDER by high-cardinality user_id within each partition for data skipping." },
{ id:223, topic:"delta", sub:"Schema", diff:"Advanced", type:"mcq", q:"A MERGE INTO fails with 'DELTA_SCHEMA_CHANGE_SINCE_ANALYSIS'. What caused this?", opts:["The target table was deleted","Another writer changed the target table schema between query planning and execution","The source DataFrame has null values","The MERGE condition is invalid"], a:1, exp:"Delta detected a schema change between query analysis and execution. Retry the MERGE — Delta's optimistic concurrency will reconcile it." },
{ id:224, topic:"delta", sub:"Maintenance", diff:"Advanced", type:"mcq", q:"How do you prevent VACUUM from deleting files still needed by a running streaming query?", opts:["Pause the stream before running VACUUM","Set delta.deletedFileRetentionDuration longer than your streaming lag","VACUUM does not affect streaming queries","Use VACUUM DRY RUN first"], a:1, exp:"Set the retention duration longer than the maximum expected streaming lag. This ensures files needed by the slowest stream checkpoint are not deleted." },
{ id:225, topic:"delta", sub:"CDF", diff:"Advanced", type:"mcq", q:"You enable CDF on a table. A downstream streaming job reads the CDF. The table undergoes REPLACE TABLE. What happens to the stream?", opts:["The stream continues normally","The stream fails — CDF cannot read across REPLACE TABLE operations","The stream skips the replaced data","REPLACE TABLE is not allowed on CDF-enabled tables"], a:1, exp:"REPLACE TABLE creates a new table at version 0, breaking the CDF stream's version continuity. The stream must be reset with a new startingVersion." },

// ══════════════════════════════════════════════════════
// TOPIC: ELT & SPARK SQL (40 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:301, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"mcq", q:"Which JOIN type returns only rows where there is a match in BOTH tables?", opts:["LEFT OUTER JOIN","RIGHT OUTER JOIN","INNER JOIN","FULL OUTER JOIN"], a:2, exp:"INNER JOIN returns only the rows that have matching values in both the left and right tables." },
{ id:302, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"tf", q:'"CTAS (CREATE TABLE AS SELECT) statements in Spark SQL inherit all constraints from the source table."', opts:["TRUE","FALSE"], a:1, exp:"CTAS creates a new table with the data from SELECT but does NOT inherit source constraints, partition specs, or table properties." },
{ id:303, topic:"elt", sub:"Auto Loader", diff:"Beginner", type:"mcq", q:"What is Auto Loader used for in Databricks?", opts:["Automatically loading cluster libraries","Incrementally ingesting new files from cloud storage as they arrive","Automatically optimizing Delta tables","Loading data from JDBC sources"], a:1, exp:"Auto Loader (cloudFiles source) efficiently processes new files arriving in cloud storage incrementally, with schema inference and evolution support." },
{ id:304, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"mcq", q:"Which function returns the number of rows in a DataFrame?", opts:[".size()","COUNT(*)","len()","df.count()"], a:3, exp:"df.count() returns the number of rows in a DataFrame as a Python long. In SQL, COUNT(*) is used." },
{ id:305, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"mcq", q:"What does SELECT DISTINCT do?", opts:["Selects all rows including duplicates","Returns only unique rows based on all selected columns","Selects only the first occurrence of each value","Sorts the results"], a:1, exp:"SELECT DISTINCT removes duplicate rows from the result set based on all columns in the SELECT list." },
{ id:306, topic:"elt", sub:"Functions", diff:"Beginner", type:"mcq", q:"Which function converts a string to uppercase in Spark SQL?", opts:["TO_UPPER()","UCASE()","UPPER()","STRING_UPPER()"], a:2, exp:"UPPER() converts a string expression to all uppercase characters in Spark SQL." },
{ id:307, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"tf", q:'"A VIEW in Spark SQL stores the actual data from the underlying query."', opts:["TRUE","FALSE"], a:1, exp:"A VIEW is a saved query — it does not store data. Each time the view is queried, the underlying SELECT statement is executed." },
{ id:308, topic:"elt", sub:"Auto Loader", diff:"Beginner", type:"mcq", q:"What format option must be set when using Auto Loader?", opts:["format('delta')","format('cloudFiles') with cloudFiles.format option","format('parquet')","format('stream')"], a:1, exp:"Auto Loader uses format('cloudFiles') with the cloudFiles.format option specifying the actual file format (json, csv, parquet, etc.)." },
{ id:309, topic:"elt", sub:"Spark SQL", diff:"Beginner", type:"mcq", q:"Which clause filters rows AFTER aggregation?", opts:["WHERE","FILTER","HAVING","LIMIT"], a:2, exp:"HAVING filters rows after GROUP BY aggregation. WHERE filters rows before aggregation." },
{ id:310, topic:"elt", sub:"Functions", diff:"Beginner", type:"mcq", q:"What does the COALESCE function do?", opts:["Combines two columns into one","Returns the first non-null value from a list of expressions","Counts non-null values","Converts nulls to empty strings"], a:1, exp:"COALESCE returns the first non-null value in the list of arguments, useful for handling NULL values." },

// --- Intermediate ---
{ id:311, topic:"elt", sub:"Auto Loader", diff:"Intermediate", type:"mcq", q:"A source adds 3 new columns. Auto Loader silently ignores them. Which setting captures new columns automatically?", opts:["cloudFiles.schemaEvolutionMode = 'addNewColumns'","cloudFiles.inferColumnTypes = true","cloudFiles.format = json","mergeSchema = true"], a:0, exp:"cloudFiles.schemaEvolutionMode = 'addNewColumns' tells Auto Loader to automatically detect and add new columns to the schema." },
{ id:312, topic:"elt", sub:"DLT", diff:"Intermediate", type:"mcq", q:"What is the key difference between a LIVE TABLE and a STREAMING LIVE TABLE in DLT?", opts:["LIVE TABLE is faster","STREAMING LIVE TABLE processes all historical data on each run","LIVE TABLE does a full recompute; STREAMING LIVE TABLE processes only new data","They are identical"], a:2, exp:"LIVE TABLE (Materialized View) recomputes fully on each pipeline run. STREAMING LIVE TABLE processes only new incremental data." },
{ id:313, topic:"elt", sub:"Spark SQL", diff:"Intermediate", type:"mcq", q:"What does the EXPLODE function do in Spark SQL?", opts:["Increases partition count","Converts an array or map column into multiple rows, one per element","Splits a string by delimiter","Expands a struct into separate columns"], a:1, exp:"EXPLODE takes an array or map column and generates a new row for each element, converting nested arrays to flat rows." },
{ id:314, topic:"elt", sub:"COPY INTO", diff:"Intermediate", type:"mcq", q:"What is the key difference between Auto Loader and COPY INTO for file ingestion?", opts:["COPY INTO supports schema evolution; Auto Loader does not","Auto Loader scales better for millions of files; COPY INTO is better for thousands","They are interchangeable","COPY INTO supports streaming; Auto Loader does not"], a:1, exp:"Auto Loader uses file notification or directory listing and scales to millions of files efficiently. COPY INTO is idempotent batch ingestion better suited for smaller file counts." },
{ id:315, topic:"elt", sub:"Spark SQL", diff:"Intermediate", type:"mcq", q:"Which window function assigns a unique sequential integer to each row within a partition?", opts:["RANK()","DENSE_RANK()","ROW_NUMBER()","NTILE()"], a:2, exp:"ROW_NUMBER() assigns a unique sequential number starting at 1 for each row within the partition, with no gaps or ties." },
{ id:316, topic:"elt", sub:"DLT", diff:"Intermediate", type:"mcq", q:"How do you define data quality expectations in a DLT pipeline?", opts:["Using CHECK constraints","Using @dlt.expect decorators","Using WHERE clauses in the query","Using Delta table properties"], a:1, exp:"DLT uses @dlt.expect, @dlt.expect_or_drop, and @dlt.expect_or_fail decorators to define and enforce data quality rules." },
{ id:317, topic:"elt", sub:"Functions", diff:"Intermediate", type:"mcq", q:"What does from_json() return when given a JSON string column?", opts:["A string with formatted JSON","A parsed struct or map based on the provided schema","An array of key-value pairs","A flattened set of columns"], a:1, exp:"from_json() parses a JSON string column and returns a struct type based on the schema you provide." },
{ id:318, topic:"elt", sub:"Spark SQL", diff:"Intermediate", type:"mcq", q:"What is a broadcast join and when is it most beneficial?", opts:["A join that broadcasts to all executors — best when both tables are large","A join that sends a small table to all executors — best when one table is small","A join that uses hash partitioning — always fastest","A join that skips the shuffle stage — only for Delta tables"], a:1, exp:"Broadcast join sends the small table to all executor nodes, avoiding the shuffle. It's most beneficial when one table is small enough to fit in memory." },
{ id:319, topic:"elt", sub:"DLT", diff:"Intermediate", type:"mcq", q:"In DLT, what does @dlt.expect_or_fail do?", opts:["Logs failed rows to a quarantine table","Drops rows that violate the expectation","Fails the entire pipeline when any row violates the expectation","Sends an alert email"], a:2, exp:"@dlt.expect_or_fail stops the entire pipeline execution when any row violates the expectation, treating it as a critical data quality failure." },
{ id:320, topic:"elt", sub:"Spark SQL", diff:"Intermediate", type:"mcq", q:"Which command in Spark SQL updates statistics for query optimization?", opts:["REFRESH TABLE","ANALYZE TABLE ... COMPUTE STATISTICS","UPDATE STATISTICS","OPTIMIZE TABLE"], a:1, exp:"ANALYZE TABLE ... COMPUTE STATISTICS gathers column-level statistics used by the Spark query optimizer for better query plans." },

// --- Advanced ---
{ id:321, topic:"elt", sub:"Auto Loader", diff:"Advanced", type:"mcq", q:"Auto Loader in file notification mode uses which cloud service on AWS?", opts:["S3 Event Notifications + SQS","CloudWatch Events","Lambda triggers","SNS only"], a:0, exp:"Auto Loader's file notification mode uses S3 Event Notifications to push events to an SQS queue, which Auto Loader then polls for new files." },
{ id:322, topic:"elt", sub:"DLT", diff:"Advanced", type:"mcq", q:"You need to run DLT in production with full isolation from development pipelines. What is the recommended approach?", opts:["Use separate notebooks","Use separate DLT pipelines with separate clusters and storage","Use different databases in the same pipeline","Use development mode with a flag"], a:1, exp:"Production and development DLT pipelines should use separate compute, separate storage locations, and separate Unity Catalog schemas for full isolation." },
{ id:323, topic:"elt", sub:"Spark SQL", diff:"Advanced", type:"mcq", q:"A Spark SQL query with a skewed join on user_id runs slowly. What is the best fix?", opts:["Increase parallelism","Use AQE skew join optimization or salting","Broadcast the large table","Add more partitions"], a:1, exp:"AQE's skew join optimization automatically splits skewed partitions. Manual salting adds a random prefix to distribute skewed keys across partitions." },
{ id:324, topic:"elt", sub:"Functions", diff:"Advanced", type:"mcq", q:"What does higher_order_function FILTER(array, x -> condition) do?", opts:["Filters rows in a DataFrame","Returns a new array containing only elements where the lambda condition is true","Applies a filter to a map type","Removes nulls from an array"], a:1, exp:"FILTER is a higher-order function that applies a lambda to each array element and returns a new array with only elements where the lambda returns true." },
{ id:325, topic:"elt", sub:"DLT", diff:"Advanced", type:"mcq", q:"A DLT streaming table reads from a Kafka source. The pipeline needs to guarantee exactly-once processing. What does DLT provide?", opts:["At-least-once only","Exactly-once via idempotent writes to Delta and Kafka offset checkpointing","Exactly-once requires manual offset management","DLT does not support Kafka"], a:1, exp:"DLT provides exactly-once processing guarantees through idempotent Delta writes combined with Kafka offset checkpointing in the pipeline state." },

// ══════════════════════════════════════════════════════
// TOPIC: INCREMENTAL PROCESSING (40 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:401, topic:"streaming", sub:"Basics", diff:"Beginner", type:"mcq", q:"What is Structured Streaming in Spark?", opts:["A batch processing framework","A fault-tolerant stream processing engine built on the Spark SQL engine","A message queue system","A real-time database"], a:1, exp:"Structured Streaming is Spark's scalable, fault-tolerant stream processing engine that treats streaming data as an unbounded table." },
{ id:402, topic:"streaming", sub:"Output Modes", diff:"Beginner", type:"mcq", q:"Which output mode writes only new rows added since the last trigger?", opts:["Complete","Update","Append","Overwrite"], a:2, exp:"Append mode outputs only new rows added to the result table since the last trigger. Complete mode rewrites the entire result." },
{ id:403, topic:"streaming", sub:"Triggers", diff:"Beginner", type:"mcq", q:"Which trigger processes all available data and then stops the stream?", opts:["Trigger.ProcessingTime('1 minute')","Trigger.Once()","Trigger.Continuous('1 second')","Trigger.AvailableNow()"], a:3, exp:"Trigger.AvailableNow() processes all available data in multiple micro-batches then stops. It replaced Trigger.Once() in newer Spark versions." },
{ id:404, topic:"streaming", sub:"Checkpointing", diff:"Beginner", type:"tf", q:'"Checkpointing in Structured Streaming is optional and only needed for fault tolerance."', opts:["TRUE","FALSE"], a:1, exp:"Checkpointing is required for stateful operations and fault recovery. Without it, streams cannot recover from failures and stateful queries will fail." },
{ id:405, topic:"streaming", sub:"Sources", diff:"Beginner", type:"mcq", q:"Which of these is NOT a built-in streaming source in Spark?", opts:["Kafka","Delta Lake","MySQL binlog (directly)","File source"], a:2, exp:"MySQL binlog is not a built-in Spark streaming source. Kafka, Delta Lake (as a stream), and file sources are natively supported." },
{ id:406, topic:"streaming", sub:"Basics", diff:"Beginner", type:"mcq", q:"What is a micro-batch in Structured Streaming?", opts:["A very small DataFrame","A small Spark job processing a bounded chunk of streaming data at regular intervals","A single Kafka message","A checkpoint interval"], a:1, exp:"In micro-batch mode, Structured Streaming periodically processes new data as small batch jobs, trading some latency for throughput and exactly-once guarantees." },
{ id:407, topic:"streaming", sub:"Output Modes", diff:"Beginner", type:"tf", q:'"Append output mode can be used with aggregations that do not use watermarking."', opts:["TRUE","FALSE"], a:1, exp:"Append mode with aggregations requires watermarking to know when aggregation results are final. Without watermarks, only Complete mode works for aggregations." },
{ id:408, topic:"streaming", sub:"Triggers", diff:"Beginner", type:"mcq", q:"What is the default trigger interval if no trigger is specified in a Structured Streaming query?", opts:["500ms","1 second","As fast as possible (0ms)","5 seconds"], a:2, exp:"Without specifying a trigger, Structured Streaming runs micro-batches as fast as possible — processing new data immediately after the previous batch completes." },
{ id:409, topic:"streaming", sub:"Checkpointing", diff:"Beginner", type:"mcq", q:"Where should the checkpoint location be stored for a production streaming job?", opts:["In the driver's local filesystem","In DBFS or cloud object storage (S3, ADLS, GCS)","In memory","In the Delta table being written to"], a:1, exp:"Checkpoint locations must be in durable, distributed storage (cloud object storage or DBFS) so they survive cluster restarts and failures." },
{ id:410, topic:"streaming", sub:"DLT", diff:"Beginner", type:"mcq", q:"What does DLT stand for in Databricks?", opts:["Data Lake Tables","Delta Live Tables","Distributed Load Tables","Data Lineage Tracking"], a:1, exp:"DLT stands for Delta Live Tables — a framework for building reliable, maintainable data pipelines with built-in data quality and lineage." },

// --- Intermediate ---
{ id:411, topic:"streaming", sub:"Watermarks", diff:"Intermediate", type:"mcq", q:"Watermarking in Structured Streaming is used to:", opts:["Set checkpointing intervals","Define how late event-time data is tolerated before being dropped from aggregations","Mark data quality issues","Encrypt streaming data"], a:1, exp:"Watermarks define the maximum allowed lateness for event-time data. Data arriving later than the watermark threshold is dropped from aggregations." },
{ id:412, topic:"streaming", sub:"DLT", diff:"Intermediate", type:"tf", q:'"DLT pipelines support both Triggered and Continuous execution modes."', opts:["TRUE","FALSE"], a:0, exp:"DLT supports Triggered mode (runs once on demand or scheduled) and Continuous mode (runs indefinitely, processing data as it arrives)." },
{ id:413, topic:"streaming", sub:"Stateful", diff:"Intermediate", type:"mcq", q:"Which Structured Streaming operation maintains state across micro-batches?", opts:["map()","filter()","groupBy().agg()","select()"], a:2, exp:"Aggregations with groupBy() maintain state across micro-batches, tracking running totals, counts, etc. across the unbounded stream." },
{ id:414, topic:"streaming", sub:"Watermarks", diff:"Intermediate", type:"mcq", q:"You set a watermark of 10 minutes on event_time. An event arrives 15 minutes late. What happens?", opts:["It is processed normally","It updates the existing aggregate","It is dropped and not included in any aggregate","It is stored in a late data table"], a:2, exp:"Events arriving later than the watermark threshold (10 min) are dropped. They will not be included in any aggregation result." },
{ id:415, topic:"streaming", sub:"Kafka", diff:"Intermediate", type:"mcq", q:"When reading from Kafka in Structured Streaming, what does the 'earliest' startingOffsets option do?", opts:["Reads only new messages from now","Reads from the beginning of the topic's retained messages","Reads from the last committed offset","Reads the latest available offset only"], a:1, exp:"startingOffsets='earliest' begins reading from the earliest available offset in each Kafka partition, processing all retained historical messages." },
{ id:416, topic:"streaming", sub:"DLT", diff:"Intermediate", type:"mcq", q:"In DLT, how do you create a streaming table that reads from a Kafka topic?", opts:["Use @dlt.table with spark.readStream.format('kafka')","Use @dlt.streaming_table decorator","Use create_streaming_live_table() function","Both A and B — @dlt.table automatically detects streaming sources"], a:3, exp:"DLT automatically determines if a table is streaming based on whether the query uses readStream. @dlt.table and @dlt.expect work the same way for both batch and streaming." },
{ id:417, topic:"streaming", sub:"Stateful", diff:"Intermediate", type:"mcq", q:"What is the purpose of mapGroupsWithState in Structured Streaming?", opts:["Applies a function to each partition","Allows custom stateful processing with arbitrary state per group key","Merges multiple streams","Applies watermarks automatically"], a:1, exp:"mapGroupsWithState enables custom stateful processing where you define how state is updated and expired for each key group." },
{ id:418, topic:"streaming", sub:"Output Modes", diff:"Intermediate", type:"mcq", q:"Which sink supports all three output modes (Append, Update, Complete)?", opts:["Delta Lake","Kafka","console","memory"], a:2, exp:"The console sink supports all three output modes and is useful for debugging. Delta Lake supports Append and Complete. Kafka supports Append and Update." },
{ id:419, topic:"streaming", sub:"Checkpointing", diff:"Intermediate", type:"mcq", q:"What happens if you change the query of a streaming job that already has a checkpoint?", opts:["The checkpoint is automatically updated","The job fails — you must delete the checkpoint and restart","Databricks merges the old and new query","The old query continues until the checkpoint expires"], a:1, exp:"Changing a streaming query's logic (sources, transformations, sinks) is incompatible with existing checkpoints. You must delete the checkpoint and restart." },
{ id:420, topic:"streaming", sub:"DLT", diff:"Intermediate", type:"mcq", q:"Which DLT feature automatically tracks and displays data lineage across pipeline tables?", opts:["Delta table history","DLT event log","Pipeline graph in the DLT UI","Unity Catalog lineage only"], a:2, exp:"The DLT pipeline graph in the UI automatically visualizes data lineage, showing how data flows through all tables and transformations in the pipeline." },

// --- Advanced ---
{ id:421, topic:"streaming", sub:"Stateful", diff:"Advanced", type:"mcq", q:"You need a streaming aggregation that emits results every 5 minutes but uses 1-hour windows. What trigger and window combination works?", opts:["Trigger.ProcessingTime('1 hour') + 1 hour tumbling window","Trigger.ProcessingTime('5 minutes') + 1 hour sliding window with watermark","Trigger.AvailableNow() + 1 hour window","Trigger.Once() + 5 minute window"], a:1, exp:"ProcessingTime('5 minutes') triggers micro-batches every 5 min, while the 1-hour sliding window with watermark accumulates state across those batches." },
{ id:422, topic:"streaming", sub:"Kafka", diff:"Advanced", type:"mcq", q:"A Kafka stream has 100 partitions. How does Spark determine the number of tasks per micro-batch?", opts:["Always 100 tasks (1 per partition)","Determined by spark.sql.shuffle.partitions","One task per Kafka partition per micro-batch by default","Determined by maxOffsetsPerTrigger divided by partitions"], a:2, exp:"By default, Structured Streaming creates one task per Kafka partition per micro-batch. maxOffsetsPerTrigger can limit offsets read per trigger." },
{ id:423, topic:"streaming", sub:"Stateful", diff:"Advanced", type:"mcq", q:"What is the risk of using flatMapGroupsWithState with GroupStateTimeout.EventTimeTimeout incorrectly?", opts:["Sessions never expire","State grows unboundedly, causing OOM on executors","The stream switches to batch mode","Checkpointing becomes impossible"], a:1, exp:"Without proper timeout configuration or watermark alignment, state for inactive groups is never cleaned up, causing state store size to grow indefinitely." },
{ id:424, topic:"streaming", sub:"DLT", diff:"Advanced", type:"mcq", q:"A DLT pipeline in Continuous mode encounters a bad batch that causes all expectations to fail. What is the safest recovery strategy?", opts:["Delete the pipeline and recreate","Use FULL_REFRESH to reprocess all data","Investigate the DLT event log, fix the source data, then resume the pipeline","Increase the expectation thresholds"], a:2, exp:"The DLT event log contains detailed information about failures. Fix the root cause in the source data, then resume. FULL_REFRESH should be used sparingly as it reprocesses all data." },
{ id:425, topic:"streaming", sub:"Watermarks", diff:"Advanced", type:"mcq", q:"You join two streams with different watermarks. How does Spark determine the effective watermark for the join?", opts:["Uses the maximum of the two watermarks","Uses the minimum of the two watermarks","Uses the average","Uses only the left stream's watermark"], a:1, exp:"Spark uses the minimum watermark across all streams in a join to ensure both sides have received all data up to that point before emitting join results." },

// ══════════════════════════════════════════════════════
// TOPIC: PRODUCTION WORKFLOWS (38 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:501, topic:"production", sub:"Jobs", diff:"Beginner", type:"mcq", q:"What is a Databricks Job?", opts:["A notebook that runs interactively","A scheduled or triggered automated execution of notebooks, scripts, or pipelines","A cluster configuration template","A Git repository connection"], a:1, exp:"A Databricks Job is a non-interactive, automated execution mechanism that can run notebooks, Python scripts, JARs, DLT pipelines, and more." },
{ id:502, topic:"production", sub:"Jobs", diff:"Beginner", type:"tf", q:'"A Databricks Job can only run a single notebook per job run."', opts:["TRUE","FALSE"], a:1, exp:"Multi-task jobs allow you to run multiple tasks (notebooks, scripts, JARs, DLT pipelines) with dependencies between them in a single job." },
{ id:503, topic:"production", sub:"Alerts", diff:"Beginner", type:"mcq", q:"How can you be notified when a Databricks Job fails?", opts:["Only through the Databricks UI","By configuring email or webhook notifications in the job settings","By checking the cluster logs manually","Using only Databricks SQL alerts"], a:1, exp:"Databricks Jobs support email and webhook (Slack, PagerDuty, etc.) notifications on job start, success, failure, and other events." },
{ id:504, topic:"production", sub:"CICD", diff:"Beginner", type:"mcq", q:"What are Databricks Asset Bundles (DABs) used for?", opts:["Managing DBFS files","Defining, deploying, and running Databricks resources (jobs, pipelines, clusters) as code using YAML","Packaging Python libraries for clusters","Managing cluster permissions"], a:1, exp:"DABs allow you to define Databricks resources in YAML configuration files, enabling CI/CD deployment of jobs, pipelines, and infrastructure as code." },
{ id:505, topic:"production", sub:"Jobs", diff:"Beginner", type:"mcq", q:"What is the maximum number of job runs Databricks retains in the run history by default?", opts:["10","25","60","Unlimited"], a:2, exp:"Databricks retains up to 60 days or 25 most recent runs of job run history, whichever limit is reached first." },
{ id:506, topic:"production", sub:"Clusters", diff:"Beginner", type:"tf", q:'"Job clusters are shared between multiple jobs to reduce costs."', opts:["TRUE","FALSE"], a:1, exp:"Each job run gets its own dedicated job cluster by default. Clusters are not shared between different jobs unless explicitly configured with shared job clusters." },
{ id:507, topic:"production", sub:"Jobs", diff:"Beginner", type:"mcq", q:"Which scheduling option runs a Databricks job at regular time intervals?", opts:["Trigger-based execution","Cron-based scheduling","Manual runs only","Event-driven execution"], a:1, exp:"Databricks Jobs support cron-based scheduling using standard cron syntax or the UI schedule builder to run jobs at regular intervals." },
{ id:508, topic:"production", sub:"CICD", diff:"Beginner", type:"mcq", q:"Which command deploys resources defined in a Databricks Asset Bundle?", opts:["dab run","databricks bundle deploy","databricks deploy --bundle","bundle push"], a:1, exp:"The 'databricks bundle deploy' command deploys the resources defined in the DAB configuration to the target Databricks workspace." },

// --- Intermediate ---
{ id:509, topic:"production", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"Where do you find detailed Spark execution plans and stage metrics for a completed job?", opts:["Cluster logs","Spark UI accessible via the Jobs tab","DBFS audit logs","Workflow email alerts"], a:1, exp:"The Spark UI (accessible from the job run details page) shows DAGs, stage details, task metrics, and execution plans for completed runs." },
{ id:510, topic:"production", sub:"CICD", diff:"Intermediate", type:"tf", q:'"Databricks Asset Bundles can only be deployed through GitHub Actions."', opts:["TRUE","FALSE"], a:1, exp:"DABs are CI/CD-agnostic and work with any CI/CD system: GitHub Actions, Azure DevOps, GitLab CI, Jenkins, or directly from the terminal." },
{ id:511, topic:"production", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"A job with 5 tasks fails at task 3. Which tasks re-run when you click 'Repair Run'?", opts:["All 5 tasks","Only task 3","Task 3 and all downstream dependent tasks","Only tasks 4 and 5"], a:2, exp:"Repair Run re-runs the failed task and all downstream tasks that depend on it, skipping the already-successful upstream tasks." },
{ id:512, topic:"production", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"What is the difference between job-level and task-level retry settings?", opts:["They are identical","Task-level retries retry a single failed task; job-level retries restart the entire job run","Job-level retries only apply to cluster failures","Task-level retries require a separate cluster per retry"], a:1, exp:"Task retries re-attempt the specific failed task. Job retries restart the entire job run from the beginning after all task retries are exhausted." },
{ id:513, topic:"production", sub:"CICD", diff:"Intermediate", type:"mcq", q:"In a DABs configuration, what does the 'target' concept represent?", opts:["A specific notebook to run","A deployment environment (dev, staging, prod) with its own settings","A cluster configuration","A storage location"], a:1, exp:"Targets in DABs represent deployment environments. Each target can have different settings (workspace URL, cluster configs, permissions) for dev/staging/prod." },
{ id:514, topic:"production", sub:"Monitoring", diff:"Intermediate", type:"mcq", q:"Which Databricks feature provides audit logs of all user and system actions in a workspace?", opts:["Cluster logs","Audit log delivery to cloud storage","Databricks SQL query history","Spark event logs only"], a:1, exp:"Databricks Audit Log delivers detailed records of all workspace actions to cloud storage (S3, ADLS), enabling compliance and security monitoring." },
{ id:515, topic:"production", sub:"Jobs", diff:"Intermediate", type:"mcq", q:"You need a job to run only after another separate job completes successfully. How do you configure this?", opts:["Use task dependencies within a single job","Use job triggers with 'After other job' condition","This is not possible in Databricks","Use a shared checkpoint between jobs"], a:1, exp:"Databricks Jobs support job triggers that fire based on the completion of another job, enabling cross-job orchestration." },
{ id:516, topic:"production", sub:"CICD", diff:"Intermediate", type:"mcq", q:"What does 'databricks bundle validate' do before deploying?", opts:["Runs all notebooks in the bundle","Validates the bundle YAML configuration for syntax and schema errors","Tests cluster connectivity","Checks permissions on all resources"], a:1, exp:"'databricks bundle validate' parses and validates the bundle configuration files, checking for YAML syntax errors and schema violations before deployment." },

// --- Advanced ---
{ id:517, topic:"production", sub:"Jobs", diff:"Advanced", type:"mcq", q:"A job runs fine in dev but fails in prod with OOM errors. Dev uses a 4-node cluster, prod uses a 2-node cluster. The fix should be:", opts:["Increase prod cluster size","Optimize the job to handle the smaller cluster: increase partitions, reduce shuffle size, optimize joins","Both A and B","Add more memory to the driver only"], a:2, exp:"Both approaches are valid. Ideally optimize the code for efficiency first, then scale the cluster if optimization isn't sufficient." },
{ id:518, topic:"production", sub:"CICD", diff:"Advanced", type:"mcq", q:"You need different cluster configs for dev and prod in a DAB. How do you achieve this without duplicating job definitions?", opts:["Create separate bundle.yml files for each environment","Use target-level cluster overrides in the DAB targets section","This requires separate Git branches","Use environment variables in the cluster config"], a:1, exp:"DABs support target-level variable overrides that allow dev and prod targets to use different cluster sizes, instance types, and configs within one bundle definition." },
{ id:519, topic:"production", sub:"Monitoring", diff:"Advanced", type:"mcq", q:"Which system table in Unity Catalog contains information about all job runs across the workspace?", opts:["system.access.audit","system.billing.usage","system.lakeflow.job_run_timeline","system.compute.clusters"], a:2, exp:"system.lakeflow.job_run_timeline contains detailed job run history including status, duration, cluster usage, and task-level details for all workspace jobs." },
{ id:520, topic:"production", sub:"Jobs", diff:"Advanced", type:"mcq", q:"A critical pipeline must complete within 2 hours. If it runs longer, it should fail and alert. How do you configure this?", opts:["Use a separate monitoring job","Set a job-level timeout in the job settings with an email alert on failure","Use cluster auto-termination","Use a Databricks SQL alert"], a:1, exp:"Job-level timeout setting terminates the run if it exceeds the specified duration. Combined with failure email notifications, this provides automatic SLA breach alerting." },

// ══════════════════════════════════════════════════════
// TOPIC: DATA GOVERNANCE (39 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:601, topic:"governance", sub:"Unity Catalog", diff:"Beginner", type:"mcq", q:"In Unity Catalog, what is the correct 3-level namespace order?", opts:["schema.catalog.table","catalog.schema.table","table.schema.catalog","database.schema.table"], a:1, exp:"Unity Catalog uses catalog.schema.table — a three-level hierarchy providing an additional layer of organization above the traditional database.table." },
{ id:602, topic:"governance", sub:"Unity Catalog", diff:"Beginner", type:"tf", q:'"Unity Catalog is workspace-scoped, meaning each Databricks workspace has its own separate Unity Catalog."', opts:["TRUE","FALSE"], a:1, exp:"Unity Catalog is account-level, not workspace-level. A single Metastore is shared across multiple workspaces in a Databricks account." },
{ id:603, topic:"governance", sub:"Permissions", diff:"Beginner", type:"mcq", q:"Which privilege allows a user to query data from a table in Unity Catalog?", opts:["MODIFY","USE CATALOG","SELECT","READ FILES"], a:2, exp:"SELECT grants the ability to query data from a table or view. USE CATALOG and USE SCHEMA are also required to navigate to the table." },
{ id:604, topic:"governance", sub:"Unity Catalog", diff:"Beginner", type:"mcq", q:"What is a Unity Catalog Metastore?", opts:["A database that stores table data","The top-level container for all Unity Catalog objects, one per Databricks account region","A type of cluster for governance","A schema for storing metadata"], a:1, exp:"A Metastore is the top-level organizational construct in Unity Catalog, containing catalogs, schemas, and tables. One Metastore is created per region per Databricks account." },
{ id:605, topic:"governance", sub:"Permissions", diff:"Beginner", type:"mcq", q:"What does GRANT SELECT ON TABLE do in Unity Catalog?", opts:["Gives ownership of the table","Allows querying data from the table","Allows modifying the table structure","Allows deleting the table"], a:1, exp:"GRANT SELECT ON TABLE gives the specified principal the ability to query (read) data from that table." },
{ id:606, topic:"governance", sub:"Unity Catalog", diff:"Beginner", type:"tf", q:'"External tables in Unity Catalog store their data in the Unity Catalog managed storage location."', opts:["TRUE","FALSE"], a:1, exp:"External tables store data in a user-specified external location. Managed tables store data in the UC-managed storage location." },
{ id:607, topic:"governance", sub:"Lineage", diff:"Beginner", type:"mcq", q:"What does Unity Catalog Data Lineage track?", opts:["Only table creation events","How data flows from source tables through transformations to downstream tables and dashboards","User login history","Cluster usage by table"], a:1, exp:"UC lineage automatically captures how data flows: which tables were read to produce which tables, including notebook, job, and SQL query lineage." },
{ id:608, topic:"governance", sub:"Permissions", diff:"Beginner", type:"mcq", q:"Which role can manage all objects within a specific catalog in Unity Catalog?", opts:["Workspace admin","Catalog owner","Account admin only","Metastore admin"], a:1, exp:"The catalog owner has full control over all objects within that catalog, including granting permissions and creating/modifying schemas and tables." },

// --- Intermediate ---
{ id:609, topic:"governance", sub:"Unity Catalog", diff:"Intermediate", type:"mcq", q:"You need to audit who queried a sensitive table last week. Where do you look?", opts:["Unity Catalog UI table details","Delta table DESCRIBE HISTORY","Cluster driver logs","System tables (system.access.audit)"], a:3, exp:"system.access.audit in Unity Catalog system tables records all data access events, permission changes, and workspace actions for audit purposes." },
{ id:610, topic:"governance", sub:"Unity Catalog", diff:"Intermediate", type:"mcq", q:"How do you set a default catalog for a Databricks session?", opts:["USE CATALOG catalog_name","SET spark.sql.catalog = catalog_name","Only in workspace admin settings","USE DATABASE catalog_name"], a:0, exp:"USE CATALOG catalog_name sets the default catalog for the current session, so queries can reference schemas and tables without the catalog prefix." },
{ id:611, topic:"governance", sub:"Permissions", diff:"Intermediate", type:"mcq", q:"What is the difference between a Managed table and an External table in Unity Catalog?", opts:["No difference","Managed tables have UC manage both metadata and data lifecycle; External tables are user-managed storage","External tables support ACID; Managed do not","Managed tables cannot be shared via Delta Sharing"], a:1, exp:"Dropping a managed table deletes both metadata and data. Dropping an external table removes only the metadata — the data files remain in the external location." },
{ id:612, topic:"governance", sub:"Unity Catalog", diff:"Intermediate", type:"mcq", q:"What is a Unity Catalog External Location?", opts:["A URL stored in a secret scope","A UC object that stores credentials and a cloud storage path, allowing Spark to access external data securely","A mount point on DBFS","A cross-region replication target"], a:1, exp:"An External Location maps a cloud storage path (e.g., s3://my-bucket/path) to a Storage Credential, allowing UC to govern access to external data." },
{ id:613, topic:"governance", sub:"Lineage", diff:"Intermediate", type:"mcq", q:"Unity Catalog lineage is captured for which types of operations?", opts:["Only DLT pipelines","Notebooks, Jobs, SQL queries, and DLT pipelines","Only scheduled jobs","Only Delta table writes"], a:1, exp:"UC captures column-level lineage for operations executed through notebooks, Databricks SQL queries, Jobs, and DLT pipelines." },
{ id:614, topic:"governance", sub:"Permissions", diff:"Intermediate", type:"mcq", q:"How do you implement row-level security in Unity Catalog?", opts:["Using WHERE clauses in views","Using ROW FILTER policies assigned to tables","Using Apache Ranger","Using Spark SQL ACLs"], a:1, exp:"UC supports native Row Filters — SQL functions assigned to tables that automatically filter rows based on the querying user's attributes or group membership." },
{ id:615, topic:"governance", sub:"Unity Catalog", diff:"Intermediate", type:"mcq", q:"What is a Storage Credential in Unity Catalog?", opts:["A Databricks secret storing a password","A UC object encapsulating cloud IAM credentials (service principal, managed identity) for accessing cloud storage","A DBFS mount configuration","A cluster-level IAM role"], a:1, exp:"A Storage Credential is a UC object that securely stores cloud IAM credentials, referenced by External Locations to grant Spark access to cloud storage." },
{ id:616, topic:"governance", sub:"Permissions", diff:"Intermediate", type:"mcq", q:"A user needs to create new tables in a schema. Which minimum set of privileges is required?", opts:["SELECT on schema","CREATE TABLE on schema + USE SCHEMA + USE CATALOG","MODIFY on catalog","OWNER of catalog"], a:1, exp:"To create tables, a user needs: USE CATALOG (navigate to catalog), USE SCHEMA (navigate to schema), and CREATE TABLE (create objects in schema)." },

// --- Advanced ---
{ id:617, topic:"governance", sub:"Unity Catalog", diff:"Advanced", type:"mcq", q:"Your team uses both AWS and Azure workspaces. They need to share Delta tables without copying data. What is the correct approach?", opts:["Cross-cloud DBFS mount","Delta Sharing with a Unity Catalog share object","Data replication via ETL","External tables with shared S3 bucket"], a:1, exp:"Delta Sharing via UC Share objects enables cross-cloud, cross-platform data sharing. Recipients access live data without it being copied to their storage." },
{ id:618, topic:"governance", sub:"Permissions", diff:"Advanced", type:"mcq", q:"A column contains PII. You need to mask it for non-privileged users while showing plaintext to data owners. What UC feature enables this?", opts:["Column encryption","Column Masks — SQL masking functions assigned at the column level","Row Filters with column conditions","GRANT on specific columns only"], a:1, exp:"UC Column Masks apply a masking function at query time based on the user's identity, showing masked values to non-privileged users and plaintext to authorized users." },
{ id:619, topic:"governance", sub:"Unity Catalog", diff:"Advanced", type:"mcq", q:"You need to enforce that only specific service principals can write to production Delta tables, regardless of notebook permissions. What is the cleanest approach?", opts:["Use workspace-level ACLs","Assign table ownership to the service principal and use GRANT/REVOKE in UC","Use cluster-level IAM roles only","Use DBFS permissions"], a:1, exp:"UC GRANT/REVOKE on tables, combined with service principal ownership, provides workspace-agnostic, centrally-governed access control enforced at the data layer." },

// ══════════════════════════════════════════════════════
// TOPIC: PERFORMANCE TUNING (38 questions)
// ══════════════════════════════════════════════════════

// --- Beginner ---
{ id:701, topic:"performance", sub:"Shuffle", diff:"Beginner", type:"mcq", q:"What causes a shuffle in Spark?", opts:["Reading from Delta Lake","Operations requiring data redistribution across partitions","UDF execution","Schema validation"], a:1, exp:"Shuffles occur when data must move across partitions — groupBy, join on non-partitioned keys, distinct, repartition, and coalesce are common causes." },
{ id:702, topic:"performance", sub:"Caching", diff:"Beginner", type:"mcq", q:"What does df.cache() do in Spark?", opts:["Writes data to disk permanently","Stores the DataFrame in memory (and disk if needed) for faster repeated access","Compresses the DataFrame","Materializes the DataFrame to Delta Lake"], a:1, exp:"cache() persists the DataFrame in memory across the cluster using the default MEMORY_AND_DISK storage level, avoiding recomputation on subsequent actions." },
{ id:703, topic:"performance", sub:"Partitioning", diff:"Beginner", type:"tf", q:'"More partitions always results in faster Spark job performance."', opts:["TRUE","FALSE"], a:1, exp:"Too many partitions for small data causes excessive scheduling overhead. Too few causes under-utilization. The right number depends on data size and cluster cores." },
{ id:704, topic:"performance", sub:"AQE", diff:"Beginner", type:"mcq", q:"What does AQE stand for in Spark?", opts:["Automatic Query Execution","Adaptive Query Execution","Advanced Query Engine","Asynchronous Query Evaluation"], a:1, exp:"AQE stands for Adaptive Query Execution — a Spark feature that dynamically optimizes query plans at runtime based on actual data statistics." },
{ id:705, topic:"performance", sub:"Optimization", diff:"Beginner", type:"mcq", q:"What is data skew in Spark?", opts:["Incorrect data types","Uneven distribution of data across partitions causing some tasks to take much longer than others","Missing partition columns","Null values in join keys"], a:1, exp:"Data skew occurs when partition sizes are very uneven — some partitions have much more data than others, causing a few slow tasks to bottleneck the job." },
{ id:706, topic:"performance", sub:"Caching", diff:"Beginner", type:"mcq", q:"When should you NOT cache a DataFrame?", opts:["When it is used multiple times","When it is used only once","When it is small","When it contains Delta table data"], a:1, exp:"Caching a DataFrame used only once wastes memory and adds overhead. Cache only when a DataFrame is reused multiple times in the same application." },
{ id:707, topic:"performance", sub:"Shuffle", diff:"Beginner", type:"mcq", q:"What Spark configuration controls the number of partitions after a shuffle?", opts:["spark.default.parallelism","spark.sql.shuffle.partitions","spark.task.cpus","spark.executor.cores"], a:1, exp:"spark.sql.shuffle.partitions (default 200) controls the number of partitions for shuffles triggered by SQL operations. For RDDs, use spark.default.parallelism." },
{ id:708, topic:"performance", sub:"Optimization", diff:"Beginner", type:"tf", q:'"Predicate pushdown means Spark filters data as early as possible, ideally at the data source level."', opts:["TRUE","FALSE"], a:0, exp:"Predicate pushdown optimizes queries by pushing filter conditions down to the data source (e.g., Parquet column statistics, Delta data skipping), reducing data read." },

// --- Intermediate ---
{ id:709, topic:"performance", sub:"AQE", diff:"Intermediate", type:"mcq", q:"Adaptive Query Execution (AQE) can automatically:", opts:["Rewrite SQL queries","Coalesce shuffle partitions, switch join strategies, and optimize skew joins at runtime","Cache frequently accessed tables","Reorder WHERE predicates"], a:1, exp:"AQE uses runtime statistics to dynamically coalesce small shuffle partitions, switch to broadcast joins when a table is small, and split skewed partitions." },
{ id:710, topic:"performance", sub:"Partitioning", diff:"Intermediate", type:"mcq", q:"You have a 10TB Delta table partitioned by year. Queries always filter by both year and month. What is the optimal approach?", opts:["Partition by year only","Partition by year and month","Partition by month only and ZORDER by year","Use Liquid Clustering on year and month"], a:3, exp:"Liquid Clustering on year and month columns provides more flexible and efficient data skipping than static partitioning, especially for multi-column filter patterns." },
{ id:711, topic:"performance", sub:"Broadcast", diff:"Intermediate", type:"mcq", q:"What is the default threshold for automatic broadcast joins in Spark SQL?", opts:["1MB","10MB","100MB","1GB"], a:1, exp:"spark.sql.autoBroadcastJoinThreshold defaults to 10MB. Tables smaller than this are automatically broadcast to all executors to avoid shuffle." },
{ id:712, topic:"performance", sub:"Photon", diff:"Intermediate", type:"mcq", q:"What type of workloads benefit most from Photon?", opts:["Python UDF-heavy workloads","SQL and DataFrame operations on large datasets with aggregations and joins","Small data exploration","ML model training"], a:1, exp:"Photon is a vectorized C++ query engine that accelerates SQL and DataFrame operations, especially aggregations, joins, and scans on large datasets." },
{ id:713, topic:"performance", sub:"AQE", diff:"Intermediate", type:"mcq", q:"AQE's skew join optimization works by:", opts:["Redistributing all partitions equally before the join","Splitting oversized skewed partitions and replicating the corresponding small-side partitions","Broadcasting the skewed table","Using sampling to estimate skew and repartition"], a:1, exp:"AQE detects skewed partitions (larger than the skew threshold), splits them into smaller sub-partitions, and replicates the matching small-side data to enable parallel processing." },
{ id:714, topic:"performance", sub:"Optimization", diff:"Intermediate", type:"mcq", q:"What is the purpose of ANALYZE TABLE ... COMPUTE STATISTICS?", opts:["To compact small files","To collect column-level statistics used by the Spark optimizer for better query plans","To run a data quality check","To update the partition list"], a:1, exp:"ANALYZE TABLE collects table and column statistics (min, max, distinct count, null count) that the cost-based optimizer uses to choose better join strategies and scan orders." },
{ id:715, topic:"performance", sub:"Caching", diff:"Intermediate", type:"mcq", q:"What is the difference between cache() and persist(StorageLevel.DISK_ONLY)?", opts:["No difference","cache() stores in memory first, spilling to disk if needed; DISK_ONLY writes only to disk","persist() is deprecated in favor of cache()","DISK_ONLY is faster than cache()"], a:1, exp:"cache() uses MEMORY_AND_DISK storage — data is held in memory and spills to disk when memory is full. DISK_ONLY writes exclusively to disk, using less memory but with slower access." },
{ id:716, topic:"performance", sub:"Shuffle", diff:"Intermediate", type:"mcq", q:"You have a job with 1000 partitions but each partition is only 1KB. What is the performance problem and fix?", opts:["No problem — more partitions is better","Too many small tasks cause excessive scheduling overhead; coalesce or repartition to fewer, larger partitions","Increase parallelism to match partition count","Increase spark.sql.shuffle.partitions to 2000"], a:1, exp:"Thousands of tiny partitions create excessive task scheduling overhead. Use coalesce() to reduce partitions without a shuffle, or repartition() if you need to redistribute data." },

// --- Advanced ---
{ id:717, topic:"performance", sub:"AQE", diff:"Advanced", type:"mcq", q:"AQE is enabled by default in Databricks Runtime. When would you consider disabling it?", opts:["For all streaming queries","When debugging query plans — AQE modifies plans at runtime making them harder to analyze","For small data jobs","For Python-only workloads"], a:1, exp:"AQE's runtime plan changes make it harder to reproduce and debug query execution. Temporarily disabling it (spark.sql.adaptive.enabled=false) helps isolate performance issues." },
{ id:718, topic:"performance", sub:"Photon", diff:"Advanced", type:"mcq", q:"A SQL query with a Python UDF runs significantly slower with Photon enabled than without. Why?", opts:["Photon does not support SQL","Python UDFs break the Photon native execution pipeline, causing serialization overhead between Photon and the Python runtime","Photon uses more memory for UDFs","Photon is incompatible with Python 3"], a:1, exp:"Photon executes natively in C++. Python UDFs require data to be serialized out of Photon's native format, passed to Python, then deserialized back — creating a performance bottleneck." },
{ id:719, topic:"performance", sub:"Optimization", diff:"Advanced", type:"mcq", q:"A Delta table scan takes 10 minutes despite a partition filter. EXPLAIN shows PartitionFilters is empty. What is the most likely cause?", opts:["Photon is disabled","The filter column type doesn't match the partition column type, preventing pushdown","The cluster is too small","Statistics are outdated"], a:1, exp:"Type mismatch between filter value and partition column type prevents partition pruning. Cast the filter value to match the partition column type exactly." },
{ id:720, topic:"performance", sub:"Shuffle", diff:"Advanced", type:"mcq", q:"Your Spark job uses a sortMergeJoin producing 200 shuffle partitions of wildly varying sizes (1KB to 10GB). What is the best combined approach?", opts:["Increase shuffle partitions to 2000","Enable AQE with skew join optimization + set appropriate skew thresholds + consider salting the join key","Broadcast one side of the join","Repartition both DataFrames to 200 partitions before joining"], a:1, exp:"AQE skew optimization splits oversized partitions automatically. Combined with appropriate skew thresholds (spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes), this handles most skew cases without manual salting." },
];
